import React, { useState } from "react";
import Head from "next/head";
import AddTodo from "../components/AddTodo";
import Todos from "../components/Todos";

export default function Home() {
  const currentDate = new Date();
  const [title, setTitle] = useState("Edit Title");
  const [openEditTitle, setOpenEditTitle] = useState(false);

  return (
    <div
      className="min-h-screen"
      style={{
        backgroundImage: "linear-gradient(0deg, #0093E9 0%, #80D0C7 100%)",
        backgroundColor: "#0093E9",
      }}
    >
      <Head>
        <title>Big Booster Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-7xl mx-auto">
        {openEditTitle ? (
          <div className="absolute left-0 right-0 mx-auto w-56 z-50 h-56 w-56 bg-white rounded-xl">
            <input
              onChange={(e) => {
                setTitle(e.target.value);
              }}
              className="h-12 w-fit border my-6 mx-4"
            />
            <button
              onClick={() => setOpenEditTitle(false)}
              className="bg-blue-400 w-full py-1 mx-auto text-white"
            >
              Add Title
            </button>
          </div>
        ) : null}
        <div className="py-8 text-white mx-4">
          <div className="flex gap-4">
            <h1 className="font-bold md:text-2xl text-lg">{title}</h1>
            <button
              onClick={() => setOpenEditTitle(true)}
              className="text-white bg-blue-400 px-4 py-1 flex gap-2 rounded-lg"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                />
              </svg>
              Edit Title
            </button>
          </div>

          <h2 className="">{currentDate.toDateString()}</h2>
        </div>

        <div className="grid md:grid-cols-4 grid-cols-1 mx-4 gap-4">
          <div className="md:col-span-3 ">
            <Todos />
          </div>

          <div className="col-span-1">
            <AddTodo />
          </div>
        </div>
      </main>
    </div>
  );
}
